fastlane_version "2.64.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :crashlytics do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Dropin', export_method: 'development')
    
    increment_build_number

    changelog_from_git_commits

    emails = values[:test_email] ? values[:test_email] : nil # You can list more emails here
    groups = values[:test_email] ? nil : ['ios-testing'] # You can define groups on the web and reference them here

    crashlytics(api_token: '73d334ee3bbb0f3bdc12f9ff5acd8ecaf3ca9bc7',
             build_secret: '9bd5df029781373ddfefd80ab95376e13b89ae44d95700e24b62ec3bc340173d',
                   emails: emails,
                   groups: groups,
            notifications: true) # Should this distribution notify your testers via email?

  end
  
  lane :testflight do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Dropin', export_method: 'app-store')
    
    increment_build_number

    changelog_from_git_commits

    testflight(
        username: "prattcmp@comcast.net",
        app_identifier: "com.wedropin.Dropin"
    )
  end
end
